
def vendor_db():
    return {
        '001122': 'Cisco',
        '00D0C9': 'Intel',
        'F4F5D8': 'Google',
        '3C07F4': 'Apple',
        'B827EB': 'Raspberry Pi Foundation',
        'DC4A3E': 'Raspberry Pi Trading',
        '2CF05D': 'Apple',
        '68545A': 'Apple',
        'AC87A3': 'Apple',
        '9CFC01': 'Apple',
        'F86214': 'Microsoft',
        'E8DE27': 'Microsoft',
        '00155D': 'Microsoft',
        '000569': 'Cisco',
        '001B67': 'Cisco',
        '001C0E': 'Cisco',
        '00215A': 'Cisco',
        '6C4008': 'Samsung',
        '78A873': 'Samsung',
        '885395': 'Samsung',
        'E0B9BA': 'Samsung',
        '54BF64': 'Amazon',
        'FC65DE': 'Amazon',
        '747548': 'Amazon',
        '8085C2': 'Amazon',
        'A4AE12': 'Apple',
        'A4B197': 'Samsung',
        'A4C361': 'Samsung',
        'A4D1D2': 'Apple',
        'A4DB30': 'Samsung',
        'A4E4B8': 'BlackBerry',
        'A4E975': 'Apple',
        'A4ED4E': 'ARRIS',
        'A4F1E8': 'Apple',
        'A4B805': 'Apple',
        'A4C138': 'Apple',
        'A4C3F0': 'Cisco',
        'A4D18C': 'Apple',
        'A4D18F': 'Apple',
        'A4D1D1': 'Apple',
        'A4D578': 'Texas Instruments',
        'A4D856': 'Gimbal',
        'A4E731': 'Nokia',
        'A4E991': 'Samsung',
        'A4E9A3': 'Hon Hai Precision',
        'A4EA8E': 'Extreme Networks',
        'A4EB2E': 'Microsoft',
        'A4ED43': 'IEEE Registration Authority',
        'A4EE57': 'Seiko Epson',
        'A4F3C1': 'Open Source Robotics Foundation',
        'A4F522': 'Chofu Seisakusho',
        'A4F7D0': 'LAN Accessories',
        'A4FB8D': 'Hangzhou DPTech',
        'A4FFA1': 'Samsung',
        'A8032A': 'Espressif Inc.',
        'A80600': 'Samsung',
        'A80C0D': 'Shenzhen Sundray',
        'A811FC': 'ARRIS',
        'A81374': 'Panasonic',
        'A8154D': 'Samsung',
        'A81559': 'Samsung',
        'A815D6': 'Shenzhen Meione',
        'A816B2': 'LG Electronics',
        'A81758': 'Elektronik System i Umeå',
        'A81B18': 'XTS CORP',
        'A81B5A': 'GUANGDONG OPPO MOBILE TELECOMMUNICATIONS',
        'A81B5D': 'Samsung',
        'A81D16': 'AzureWave Technology',
        'A81E84': 'Quanta Computer',
        'A81FAF': 'Krypton Polska',
        'A82066': 'Apple',
        'A823FE': 'LG Electronics',
        'A824B8': 'Nokia',
        'A825EB': 'Cambridge Industries(Group)',
        'A826D9': 'HTC Corporation',
        'A8294C': 'Precision Optical Transceivers',
        'A82BCD': 'Huawei',
        'A830BC': 'Samsung',
        'A8329A': 'Microsoft',
        'A8367A': 'frogblue TECHNOLOGY GmbH',
        'A83944': 'Actiontec',
        'A83A04': 'Apple',
        'A83B1C': 'Microsoft',
        'A83E0E': 'HMD Global',
        'A84041': 'Dragino Technology',
        'A84122': 'LG Electronics',
        'A8423F': 'Sichuan Tianyi Comheart Telecom',
        'A84481': 'Nokia',
        'A845CD': 'Siselectron Technology',
        'A845E9': 'Firich Enterprises',
        'A8474A': 'Hon Hai Precision',
        'A8494D': 'Huawei',
        'A849A5': 'Lisantech',
        'A84E3F': 'Hitron Technologies',
        'A854B2': 'Wistron Neweb',
        'A8556A': 'Pocketnet Technology',
        'A8574E': 'TP-Link',
        'A85840': 'Cambridge Industries(Group)',
        'A85AE0': 'Huawei',
        'A85B6A': 'Huawei',
        'A85BB0': 'Shenzhen Dehoo Technology',
        'A85BF3': 'Audivo GmbH',
        'A85EE4': '12Sided Technology',
        'A860B6': 'Apple',
        'A8610A': 'Aruba Networks',
        'A861AA': 'Cloudview Limited',
        'A862A2': 'JETOUR AUTOMOBILE',
        'A863DF': 'Displaire',
        'A863F2': 'Texas Instruments',
        'A86405': 'nimbus 9',
        'A865B2': 'DONGGUAN YISHANG ELECTRONIC TECHNOLOGY',
        'A8667F': 'Apple',
        'A86A6F': 'RIM',
        'A86ABB': 'Sagemcom',
        'A86AC1': 'HanbitEDS',
        'A86B7C': 'Shenzhen Fenglian Technology',
        'A86D5F': 'Raisecom Technology',
        'A86DAA': 'Intel',
        'A8705D': 'ARRIS',
        'A870A5': 'UniComm Inc.',
        'A87285': 'IDT',
        'A8741D': 'PHOENIX CoNTACT Electronics GmbH',
        'A875D6': 'FreeTek International',
        'A875E2': 'Aventura Technologies',
        'A8776F': 'Zonoff',
        'A87B39': 'Nokia',
        'A87C01': 'Samsung',
        'A87D12': 'Huawei',
        'A87E33': 'Nokia',
        'A88038': 'Shenzhen MovingComm Technology',
        'A88195': 'Samsung',
        'A881F1': 'BMEYE',
        'A88200': 'Hisense Electric',
        'A8827F': 'CIBN Oriental Network',
        'A886DD': 'Apple',
        'A88792': 'Broadband Antenna Tracking Systems',
        'A887ED': 'ARC Wireless',
        'A88808': 'Apple',
        'A88CEE': 'MicroMade Galka i Drozdz sp.j.',
        'A88D12': 'Apple',
        'A88E24': 'Apple',
        'A89042': 'Beijing Wanwei Zhongxing Technology',
        'A8913D': 'Apple',
        'A8922C': 'LG Electronics',
        'A89352': 'Shanghai Zhongmi Communication Technology',
        'A893E6': 'Jiangxi Jinggangshan Cking Communication Technology',
        'A8968A': 'Apple',
        'A897CD': 'ARRIS',
        'A898C6': 'Shinbo',
        'A8995C': 'aizo ag',
        'A89B10': 'inMotion Ltd.',
        'A89CA4': 'Furrion Limited',
        'A89D21': 'Cisco',
        'A89DD2': 'Shanghai DareGlobal Technologies',
        'A89FBA': 'Samsung',
        'A8A089': 'Tactical Communications',
        'A8A097': 'ScioTeq bvba',
        'A8A159': 'ASRock Incorporation',
        'A8A198': 'TCT Mobile',
        'A8A5E2': 'MSF-Vathauer Antriebstechnik GmbH & Co KG',
        'A8A648': 'Qingdao Hisense Communications',
        'A8A668': 'zte',
        'A8A6CD': 'Huawei',
        'A8A795': 'Hon Hai Precision',
        'A8AD3D': 'Alcatel-Lucent Shanghai Bell',
        'A8B0AE': 'Leoni',
        'A8B1D4': 'Cisco',
        'A8B2DA': 'Fujitsu Limited',
        'A8B456': 'Cisco',
        'A8B86E': 'LG Electronics',
        'A8B9B3': 'Essys',
        'A8BB50': 'WiZ IoT Company Limited',
        'A8BBCF': 'Apple',
        'A8BD1A': 'Honey Bee (Hong Kong) Limited',
        'A8BD27': 'HP',
        'A8BE27': 'Apple',
        'A8C0EA': 'Pepwave Limited',
        'A8C222': 'TM-Research',
        'A8C252': 'Huawei',
        'A8C83A': 'Huawei',
        'A8CA7B': 'Huawei',
        'A8CB95': 'East Best',
        'A8CCC5': 'Saab AB',
        'A8CE90': 'CVC',
        'A8D0E5': 'Juniper Networks',
        'A8D236': 'Lightware Visual Engineering',
        'A8D3C8': 'Topcon Electronics',
        'A8D3F7': 'Arcadyan',
        'A8D409': 'USA 111 Inc',
        'A8D498': 'Avira Operations GmbH & Co. KG',
        'A8D579': 'Beijing Chushang Science and Technology',
        'A8D828': 'Ascensia Diabetes Care',
        'A8DA01': 'Shenzhen NUOLIJIA Digital Technology',
        'A8E018': 'Nokia',
        'A8E2C1': 'Shenzhen YOUHUA Technology',
        'A8E3EE': 'Sony',
        'A8E539': 'Moimstone',
        'A8E705': 'Fiberhome',
        'A8E77D': 'Texas Instruments',
        'A8E824': 'Huawei',
        'A8EF26': 'Tritonwave',
        'A8F038': 'Shenzhen SHILIS Technology',
        'A8F274': 'Samsung',
        'A8F470': 'Fujian Newland Auto-ID Tech.',
        'A8F7E0': 'PLANET Technology',
        'A8FB70': 'WiseSec L.t.d',
        'A8FCB7': 'Consolidated Resource Imaging',
        'AA0000': 'DIGITAL EQUIPMENT',
        'AA0001': 'DIGITAL EQUIPMENT',
        'AA0002': 'DIGITAL EQUIPMENT',
        'AA0003': 'DIGITAL EQUIPMENT',
        'AA0004': 'DIGITAL EQUIPMENT',
        'AC1461': 'ATAW',
        'AC162D': 'Hewlett Packard',
        'AC1702': 'Fibar Group sp. z o.o.',
        'AC1826': 'Seiko Epson',
        'AC199F': 'Sungrow Power Supply',
        'AC1F09': 'Shenzhen RAKwireless Technology',
        'AC1F74': 'Apple',
        'AC203E': 'Wuhan Tianyu Information',
        'AC20AA': 'DMATEK',
        'AC220B': 'ASUSTek COMPUTER',
        'AC2334': 'Infinix mobility limited',
        'AC233F': 'Shenzhen Minew Technologies',
        'AC293A': 'Apple',
        'AC2A0C': 'CSR Zhuzhou Institute',
        'AC2B6E': 'Intel',
        'AC2DA3': 'TXTR GmbH',
        'AC319D': 'Shenzhen TG-NET Botone Technology',
        'AC34CB': 'Shanhai GBCOM Communication Technology',
        'AC3613': 'Samsung',
        'AC3743': 'HTC',
        'AC3870': 'Lenovo',
        'AC3A67': 'Cisco',
        'AC3A7A': 'Roku',
        'AC3C0B': 'Apple',
        'AC3CB4': 'Nilan',
        'AC3D05': 'Instorescreen Aisa',
        'AC3D75': 'HANGZHOU ZHIWAY TECHNOLOGIES',
        'AC3FA4': 'Taiyo Yuden',
        'AC40EA': 'C&T Solution',
        'AC4122': 'Eclipse',
        'AC44F2': 'Yamaha',
        'AC4723': 'Genelec',
        'AC482D': 'Ralinwi Nanjing Electronic Technology',
        'AC4AFE': 'Hisense Broadband Multimedia',
        'AC4BxC': 'Huawei',
        'AC4E91': 'Huawei',
        'AC4FFC': 'SVS-VISTEK GmbH',
        'AC5036': 'Pi-Coral',
        'AC512C': 'Infinix mobility limited',
        'AC51EE': 'Cambridge Industries(Group)',
        'AC54EC': 'IEEE P1823 Standards Working Group',
        'AC562C': 'Lantiq Deutschland GmbH',
        'AC5A14': 'Samsung',
        'AC5D10': 'Pace Americas',
        'AC5E8C': 'Utillink',
        'AC5F3E': 'Samsung',
        'AC6089': 'Huawei',
        'AC60B6': 'Ericsson',
        'AC6123': 'Drivven',
        'AC6175': 'Huawei',
        'AC61EA': 'Apple',
        'AC620D': 'Jabil Circuit',
        'AC63BE': 'Amazon',
        'AC6462': 'ZTE',
        'AC64CF': 'FN-Link Technology Limited',
        'AC675D': 'Intel',
        'AC676F': 'Electrocompaniet A.S.',
        'AC6B0F': 'Cadence Design Systems',
        'AC6BAC': 'Jenny Science',
        'AC6E1A': 'Shenzhen Gongjin Electronics',
        'AC6F4F': 'Enspert',
        'AC6FBB': 'TATUNG Technology',
        'AC6FD9': 'Valueplus',
        'AC7236': 'Lexking Technology',
        'AC7289': 'Intel',
        'AC7409': 'Hangzhou Hikvision Digital Technology',
        'AC7A42': 'iConnectivity',
        'AC7BA1': 'Intel',
        'AC7E8A': 'Cisco',
        'AC7F3E': 'Apple',
        'AC80D6': 'Hexatronic',
        'AC8112': 'Gemtek Technology',
        'AC81F3': 'Nokia',
        'AC8317': 'Shenzhen Furtunetel Technology',
        'AC83F0': 'ImmediaTV',
        'AC83F3': 'AMPAK Technology',
        'AC853D': 'Huawei',
        'AC8674': 'Open Mesh',
        'AC867E': 'Create New Technology (HK) Limited',
        'AC87A3': 'Apple',
        'AC8995': 'AzureWave Technology',
        'AC8ACD': 'ROGER D.Wensker',
        'AC8D14': 'Smartrove',
        'AC932F': 'Nokia',
        'AC9403': 'Envision Peripherals',
        'AC9A22': 'NXP Semiconductors',
        'AC9A96': 'Lantiq Deutschland GmbH',
        'AC9B0A': 'Sony',
        'AC9B84': 'Smak Tecnologia e Automacao',
        'AC9CE4': 'Alcatel-Lucent Shanghai Bell',
        'AC9E17': 'ASUSTek COMPUTER',
        'ACA016': 'Cisco',
        'ACA22C': 'Baycity Technologies',
        'ACA31E': 'Aruba Networks',
        'ACA430': 'Peerless AV',
        'ACA919': 'TrekStor',
        'ACA9A0': 'Audioengine',
        'ACAB2E': 'Beijing LasNubes Technology',
        'ACAB8D': 'Lyngso Marine',
        'ACABBF': 'AthenTek',
        'ACB313': 'ARRIS',
        'ACB57D': 'Liteon Technology',
        'ACB74F': 'METEL s.r.o.',
        'ACB859': 'Uniband Electronic',
        'ACBC32': 'Apple',
        'ACBD0B': 'Leimac',
        'ACBE75': 'Ufine Technologies',
        'ACBEB6': 'Visualedge Technology',
        'ACC1EE': 'Xiaomi',
        'ACC2EC': 'CLT INT\'L IND. CORP.',
        'ACC33A': 'Samsung',
        'ACC51B': 'Zhuhai Pantum Electronics',
        'ACC595': 'Graphite Systems',
        'ACC662': 'MitraStar Technology',
        'ACC698': 'Kohzu Precision',
        'ACC73F': 'Vitsmo',
        'ACC935': 'Ness',
        'ACCA54': 'Telldus Technologies',
        'ACCA8E': 'ODA Technologies',
        'ACCAAB': 'Virtual Electric',
        'ACCB09': 'Hefcom Metering',
        'ACCC8E': 'Axis',
        'ACCE8F': 'HWA YAO TECHNOLOGIES',
        'ACCF23': 'Hi-flying electronics technology',
        'ACCF5C': 'Apple',
        'ACCF85': 'Huawei',
        'ACD074': 'Espressif Inc.',
        'ACD180': 'Crexendo',
        'ACD1B8': 'Hon Hai Precision',
        'ACD364': 'ABB',
        'ACD657': 'Shaanxi Guolian Digital TV Technology',
        'ACD9D6': 'tci GmbH',
        'ACDBDA': 'Shenzhen Geniatech',
        'ACDE48': 'Private',
        'ACDFC1': 'Huawei',
        'ACE010': 'Liteon Technology',
        'ACE069': 'ISAAC Instruments',
        'ACE215': 'Huawei',
        'ACE348': 'MadgeTech',
        'ACE42E': 'SK hynix',
        'ACE4B5': 'Shenzhen Baojia Battery Technology',
        'ACE5F0': 'Doppler Labs',
        'ACE64B': 'Shenzhen Baojia Battery Technology',
        'ACE77B': 'Sichuan Tianyi Comheart Telecom',
        'ACE87B': 'Huawei',
        'ACE87E': 'Bytemark Computer',
        'ACE97F': 'IoT Tech',
        'ACE9AA': 'Hay Systems',
        'ACEA6A': 'GENIX INFOCOMM',
        'ACEC80': 'ARRIS',
        'ACEE3B': '6harmonics',
        'ACEE9E': 'Samsung',
        'ACF0B2': 'Becker',
        'ACF1DF': 'D-Link',
        'ACF2C5': 'Cisco',
        'ACF7F3': 'Xiaomi',
        'ACF85C': 'Private',
        'ACF97E': 'ELESYS',
        'ACFD93': 'Weifang Goertek Electronics',
        'ACFDCE': 'Intel',
        'ACFDEC': 'Apple',
        'B000B4': 'Cisco',
        'B00484': 'Shenzhen SuperElectron Technology',
        'B00594': 'Liteon Technology',
        'B008BF': 'Vital Connect',
        'B009D3': 'Avizia',
        'B00CD1': 'Fiberhome',
        'B01041': 'Hon Hai Precision',
        'B01266': 'Futaba-Kikaku',
        'B01408': 'LIGHTSPEED',
        'B015B7': 'ZTE',
        'B01743': 'EDISON GLOBAL CIRCUITS',
        'B01886': 'SmarDTV',
        'B01B7C': 'Ontrol',
        'B01BD2': 'Le Shi Zhi Xin Electronic Technology',
        'B01C91': 'Elim Co',
        'B01F81': 'IEEE Registration Authority',
        'B024F3': 'Progeny Systems',
        'B025AA': 'Private',
        'B03495': 'Apple',
        'B0358D': 'Nokia',
        'B0359F': 'Intel',
        'B03829': 'Siliconware Precision Industries',
        'B03850': 'Nanjing CAS-ZDC IOT SYSTEM',
        'B03EB0': 'MICRODIA',
        'B04089': 'Senient Systems',
        'B0411D': 'ITTIM',
        'B0435D': 'NuLEDs',
        'B04515': 'mira fitness',
        'B04519': 'TCT Mobile',
        'B04545': 'YACOUB Automation',
        'B046FC': 'MitraStar Technology',
        'B047BF': 'Samsung',
        'B0481A': 'Apple',
        'B0487A': 'TP-Link',
        'B0495F': 'OMRON HEALTHCARE',
        'B04C05': 'Fresenius Medical Care Deutschland',
        'B050BC': 'Shenzhen Basicom Electronic',
        'B0518E': 'Holl',
        'B05216': 'Hon Hai Precision',
        'B05706': 'Vallox',
        'B058C4': 'Broadcast Microwave Services',
        'B05947': 'Shenzhen Qihu Intelligent Technology',
        'B05ADA': 'Hewlett Packard',
        'B05B1F': 'THERMO FISHER SCIENTIFIC S.P.A.',
        'B05B67': 'Huawei',
        'B05CE5': 'Nokia',
        'B061C7': 'Ericsson-LG',
        'B06563': 'Shanghai Railway Communication Factory',
        'B065BD': 'Apple',
        'B068B6': 'Hangzhou OYE Technology',
        'B06971': 'DEI Sales',
        'B06CBF': '3ality Digital Systems GmbH',
        'B0702D': 'Apple',
        'B072BF': 'Murata Manufacturing',
        'B0750C': 'QA Cafe',
        'B0754D': 'Nokia',
        'B075D5': 'ZTE',
        'B077AC': 'ARRIS',
        'B07870': 'Wi-NEXT',
        'B07908': 'Cummings',
        'B0793C': 'Revolv',
        'B07994': 'Motorola',
        'B07D47': 'Cisco',
        'B07D62': 'Dipl.-Ing. H. Horstmann',
        'B07E70': 'Zadara Storage',
        'B07FB9': 'Netgear',
        'B0808C': 'Laser Light Engines',
        'B081D8': 'I-sys',
        'B083FE': 'Dell',
        'B0869E': 'Chloride S.r.L',
        'B08807': 'Strata Worldwide',
        'B08900': 'Huawei',
        'B08991': 'LGE',
        'B08E1A': 'URadio Systems',
        'B0907E': 'Cisco',
        'B09122': 'Texas Instruments',
        'B09134': 'Taleo',
        'B09137': 'ISis ImageStream Internet Solutions',
        'B0966C': 'Lanbowan Technology',
        'B0973A': 'E-Fuel',
        'B0989F': 'LG',
        'B09928': 'FUJITSU LIMITED',
        'B09AE2': 'Steinel',
        'B09BD4': 'GNH Software',
        'B09FBA': 'Apple',
        'B0A10A': 'Pivotal Systems',
        'B0A2E7': 'Shenzhen TINNO Mobile Technology',
        'B0A37E': 'Qingdao Haier Technology',
        'B0A72A': 'Ensemble Designs',
        'B0A737': 'Roku',
        'B0A86E': 'Jiangsu Cynray IOT',
        'B0AA36': 'GUANGDONG OPPO MOBILE TELECOMMUNICATIONS',
        'B0AA77': 'Cisco',
        'B0ACFA': 'Fujitsu Limited',
        'B0ADAA': 'Avaya',
        'B0B28F': 'Sagemcom',
        'B0B2DC': 'ZyXEL Communications',
        'B0B32B': 'Slican Sp. z o.o.',
        'B0B448': 'Texas Instruments',
        'B0B5C3': 'IEEE Registration Authority',
        'B0B8D5': 'Nanjing Nengrui Auto Equipment',
        'B0BD6D': 'Echostreams Innovative Solutions',
        'B0BDA1': 'ZAKLAD ELEKTRONICZNY SIMS',
        'B0BF99': 'Wizitdongdo',
        'B0C128': 'Adler ELREHA',
        'B0C205': 'Bionime',
        'B0C287': 'Chicony Electronics',
        'B0C4E7': 'Samsung',
        'B0C554': 'D-Link',
        'B0C559': 'Samsung',
        'B0C5CA': 'IEEE Registration Authority',
        'B0C69A': 'Juniper Networks',
        'B0C745': 'Buffalo',
        'B0C83F': 'Jiangsu Cynray IOT',
        'B0C8AD': 'People Power',
        'B0C95B': 'Beijing Symtech',
        'B0CE18': 'Zhejiang shenghui lighting',
        'B0CF4D': 'MI-Zone Technology Ireland',
        'B0D09C': 'Samsung',
        'B0D2F5': 'Vello Systems',
        'B0D5CC': 'Texas Instruments',
        'B0D7C5': 'Logipix',
        'B0D7CC': 'Tridonic',
        'B0DA00': 'Cera',
        'B0DF3A': 'Samsung',
        'B0E03C': 'TCT Mobile',
        'B0E235': 'Xiaomi',
        'B0E2E5': 'Fiberhome',
        'B0E39D': 'CAT SYSTEM',
        'B0E50E': 'NRG',
        'B0E5ED': 'Huawei',
        'B0E754': '2Wire',
        'B0E892': 'Epson',
        'B0E97E': 'Advanced Micro Peripherals',
        'B0EC71': 'Samsung',
        'B0EC8F': 'GMX SAS',
        'B0ECE1': 'Private',
        'B0EE45': 'AzureWave Technology',
        'B0EE7B': 'Roku',
        'B0F1A3': 'Fengfan',
        'B0F1BC': 'Dhemax Ingenieros',
        'B0F1EC': 'AMPAK Technology',
        'B0F893': 'Shanghai MXCHIP Information Technology',
        'B0FAEB': 'Cisco',
        'B0FC0D': 'Amazon',
        'B0FC36': 'CyberTAN Technology',
        'B0FEBD': 'Private',
        'B4009C': 'CableWorld',
        'B40142': 'GCI Science',
        'B40418': 'Smartchip Integrated',
        'B40566': 'SP Best',
        'B407F9': 'Samsung',
        'B40832': 'TC',
        'B40AC6': 'DEXON Systems',
        'B40B44': 'Smartisan Technology',
        'B40B7A': 'Brusa Elektronik',
        'B40C25': 'Palo Alto',
        'B40E96': 'Heran',
        'B40EDC': 'LG-Ericsson',
        'B4107B': 'Texas Instruments',
        'B412FE': 'Qingdao Haier Technology',
        'B41308': 'Hangzhou Hikvision Digital Technology',
        'B41489': 'Cisco',
        'B41513': 'Huawei',
        'B41780': 'DTI Group',
        'B418D1': 'Apple',
        'B41DEF': 'Internet Laboratories',
        'B4218A': 'Dog Hunter',
        'B424E7': 'Codetek Technology',
        'B428F1': 'E-Prime',
        'B4293D': 'Shenzhen Urovo Technology',
        'B42A0E': 'Technicolor',
        'B42A39': 'ORBIT MERRET',
        'B42C92': 'Zhejiang Weirong Electronic',
        'B42E99': 'Giga-Byte Technology',
        'B43052': 'Huawei',
        'B431B8': 'Aviwest',
        'B4346C': 'MATSUNICHI DIGITAL TECHNOLOGY',
        'B43564': 'Fujian Tian Cheng Electron Science',
        'B435F7': 'Zhejiang Pearmain Electronics',
        'B436A9': 'Fibocom Wireless',
        'B436E3': 'Kbvision Group',
        'B43741': 'Consert',
        'B437D1': 'IEEE Registration Authority',
        'B43934': 'Pen Generations',
        'B439D6': 'ProCurve Networking by HP',
        'B43A28': 'Samsung',
        'B43DB2': 'Degreane Horizon',
        'B4417A': 'Shenzhen Gongjin Electronics',
        'B4430D': 'Broadlink',
        'B4475E': 'Avaya',
        'B447F5': 'Earda Technologies',
        'B44BD2': 'Apple',
        'B44CC2': 'NR ELECTRIC',
        'B451F9': 'NB Software',
        'B45253': 'Seagate Technology',
        'B4527D': 'Sony',
        'B4527E': 'Sony',
        'B45570': 'Borea',
        'B456B9': 'Teraspek Technologies',
        'B45861': 'CRemote',
        'B45CA4': 'Thing-talk Wireless Communication Technologies Limited',
        'B45D50': 'Aruba Networks',
        'B461FF': 'Lumigon',
        'B46238': 'Exablox',
        'B46293': 'Samsung',
        'B462AD': 'Elysia Germany',
        'B46698': 'Zealabs srl',
        'B467E9': 'Qingdao GoerTek Technology',
        'B46921': 'Intel',
        'B46D35': 'Dalian Seasky Automation',
        'B46D83': 'Intel',
        'B47356': 'Hangzhou Treebear Networking',
        'B47443': 'Samsung',
        'B47447': 'CoreOS',
        'B4749F': 'ASKEY COMPUTER CORP',
        'B4750E': 'Belkin',
        'B479A7': 'Samsung',
        'B47C29': 'Shenzhen Guzidi Technology',
        'B47C59': 'Jiangsu Hengxin Technology',
        'B47F5E': 'Foresight Manufacture',
        'B48255': 'Research Products',
        'B4827B': 'AKG Acoustics GmbH',
        'B482C5': 'Relay2',
        'B482FE': 'ASKEY COMPUTER CORP',
        'B48547': 'Amptown System',
        'B48910': 'Coster T.E. S.P.A.',
        'B48B19': 'Apple',
        'B4944E': 'WeTelecom',
        'B49842': 'zte',
        'B4994C': 'Texas Instruments',
        'B499BA': 'HP',
        'B49CDF': 'Apple',
        'B49D0B': 'BQ',
        'B49DB4': 'Axion Technologies',
        'B49EAC': 'Imagik Int\'l',
        'B49EE6': 'Shenzhen Technology',
        'B4A4B5': 'Zen Eye',
        'B4A4E3': 'Cisco',
        'B4A5A9': 'MODI',
        'B4A5EF': 'Sercomm',
        'B4A828': 'Shenzhen Concox Information Technology',
        'B4A82B': 'Histar Digital Electronics',
        'B4A898': 'Huawei',
        'B4A984': 'Symantec',
        'B4A9FC': 'Quanta Computer',
        'B4AA4D': 'Ensequence',
        'B4AB2C': 'MtM Technology',
        'B4AE2B': 'Microsoft',
        'B4AE6F': 'Circle Reliance',
        'B4B017': 'Avaya',
        'B4B15A': 'Siemens',
        'B4B265': 'DAEHO',
        'B4B362': 'ZTE',
        'B4B384': 'ShenZhen Figigantic Electronic',
        'B4B52F': 'Hewlett Packard',
        'B4B542': 'Hubbell Power Systems',
        'B4B5AF': 'Minsung',
        'B4B676': 'Intel',
        'B4B859': 'Texa',
        'B4B88D': 'Thuh',
        'B4B9B3': 'Wuhan Maritime Communication',
        'B4BA12': 'China Mobile Information',
        'B4BD7E': 'Morse Micro',
        'B4BF3F': 'Shenzhen Mercury',
        'B4C0F5': 'Shenzhen TINNO Mobile Technology',
        'B4C44E': 'VXL eTech',
        'B4C799': 'Extreme Networks',
        'B4C810': 'UMPI',
        'B4CCE9': 'Prosyst',
        'B4CFDB': 'Shenzhen Jiuzhou Electric',
        'B4CFE0': 'Sichuan AI-Link Technology',
        'B4D135': 'Cloudistics',
        'B4D5BD': 'Intel',
        'B4D8A9': 'BetterBots',
        'B4D8DE': 'iota Computing',
        'B4DD15': 'ControlThings',
        'B4DF3B': 'Chromlech',
        'B4DFFA': 'Litemax Electronics',
        'B4E0CD': 'Fusion-io',
        'B4E1C4': 'Microsoft',
        'B4E1EB': 'Private',
        'B4E62A': 'LG Innotek',
        'B4E782': 'Vivalnk',
        'B4E9B0': 'Cisco',
        'B4ED19': 'Pie Digital',
        'B4ED54': 'Wohler Technologies',
        'B4EEB4': 'ASKEY COMPUTER CORP',
        'B4EED4': 'Texas Instruments',
        'B4EF04': 'DAIHAN Scientific',
        'B4EF39': 'Samsung',
        'B4F0AB': 'Apple',
        'B4F2E8': 'ARRIS',
        'B4F323': 'PETATEL',
        'B4F81E': 'Kinova',
        'B4FBE4': 'Ubiquiti Networks',
        'B4FC75': 'SEMA Electronics',
        'B4FE8C': 'Centro Sicurezza Italia',
        'B4FF98': 'Huawei',
        'B80018': 'Htel',
        'B80305': 'Intel',
        'B80415': 'Bayan Audio',
        'B805AB': 'zte',
        'B808CF': 'Intel',
        'B808D7': 'Huawei',
        'B8098A': 'Apple',
        'B80B9D': 'ROPEX Industrie-Elektronik GmbH',
        'B810D4': 'Masimo',
        'B81413': 'Keen High Holding',
        'B81619': 'ARRIS',
        'B817C2': 'Apple',
        'B8186F': 'ORIENTAL MOTOR',
        'B81999': 'Nesys',
        'B820E7': 'Guangzhou Horizontal Information',
        'B82410': 'Magneti Marelli Slovakia s.r.o.',
        'B8241A': 'Sweda Informatic',
        'B824F0': 'SOYO Development',
        'B8259A': 'Thalmic Labs',
        'B8266C': 'ANOV France',
        'B826D4': 'Furukawa Industrial S.A. Produtos Elétricos',
        'B827EB': 'Raspberry Pi Foundation',
        'B8288B': 'Parker Hannifin Manufacturing',
        'B829F7': 'Blaster',
        'B82A72': 'Dell',
        'B82ADC': 'EFR Europäische Funk-Rundsteuerung GmbH',
        'B82CA0': 'Resideo',
        'B830A8': 'Road-Track Telematics Development',
        'B83241': 'Wuhan Tianyu Information',
        'B836D8': 'Videoswitch',
        'B83861': 'Cisco',
        'B838CA': 'Kyokko Tsushin System',
        'B83A08': 'Tenda Technology',
        'B83A7B': 'Worldplay',
        'B83D4E': 'Shenzhen Cultraview Digital Technology',
        'B83E59': 'Roku',
        'B8415F': 'ASP',
        'B843E4': 'Vlatacom',
        'B844D9': 'Apple',
        'B847C6': 'SanJet Technology',
        'B84FD5': 'Microsoft',
        'B85001': 'Extreme Networks',
        'B853AC': 'Apple',
        'B85510': 'Zioncom Electronics',
        'B856BD': 'ITT',
        'B857D8': 'Samsung',
        'B85810': 'NUMERA',
        'B85A73': 'Samsung',
        'B85AF7': 'Ouya',
        'B85AFE': 'Handaer',
        'B85E7B': 'Samsung',
        'B86091': 'Onnet Technologies',
        'B8616F': 'Accton Technology',
        'B8621F': 'Cisco',
        'B863BC': 'ROBOTIS',
        'B86491': 'CK Telecom Limited',
        'B8653B': 'Bolymin',
        'B869C2': 'Sunitec',
        'B86B23': 'Toshiba',
        'B86CE8': 'Samsung',
        'B8718E': 'Datto',
        'B87424': 'Viessmann Elektronik GmbH',
        'B87447': 'Convergence',
        'B875C0': 'PayPal',
        'B8763F': 'Hon Hai Precision',
        'B877C3': 'METER Group',
        'B8782E': 'Apple',
        'B87879': 'Roche Diagnostics',
        'B8797E': 'Secure Meters',
        'B87AC9': 'Siemens',
        'B87CF2': 'Aerohive Networks',
        'B88198': 'Intel',
        'B88687': 'Liteon Technology',
        'B8871E': 'Good Mind Innovation',
        'B887A8': 'Step Ahead Innovations',
        'B888E3': 'COMPAL INFORMATION',
        'B88981': 'Chengdu InnoThings Technology',
        'B889CA': 'ILJIN ELECTRIC',
        'B88A60': 'Intel',
        'B88D12': 'Apple',
        'B88EC6': 'Stateless Networks',
        'B88EDF': 'Zencheer',
        'B88F14': 'Analytica',
        'B8921D': 'BG T&A',
        'B894D2': 'Retail Innovation HTT',
        'B89674': 'AllDSP',
        'B8975A': 'BIOSTAR Microtech Int\'l',
        'B898B0': 'Atlona',
        'B898F7': 'Gionee Equipment',
        'B89919': '7signal',
        'B899AE': 'Shenzhen MiaoMing Intelligent Technology',
        'B899B0': 'Cohere',
        'B89A9A': 'Xin Shi Jia Technology',
        'B89ACD': 'ELITE OPTOELECTRONIC',
        'B89BC9': 'SMC',
        'B89BE4': 'ABB Power Systems Power Generation',
        'B8A386': 'D-Link',
        'B8A3E0': 'BenRui Technology',
        'B8A8AF': 'Logic S.p.A.',
        'B8AC6F': 'Dell',
        'B8AD3E': 'Bluecom',
        'B8AE6E': 'Nintendo',
        'B8AEED': 'Elitegroup',
        'B8AF67': 'Hewlett Packard',
        'B8B2EB': 'Googol Technology',
        'B8B3DC': 'Derek',
        'B8B42E': 'Gionee Equipment',
        'B8B7D7': '2GIG Technologies',
        'B8B81E': 'Intel',
        'B8B94E': 'Shenzhen iBaby',
        'B8BA68': 'Xi\'an Jizhong Digital',
        'B8BA72': 'Cynove',
        'B8BB23': 'Guangdong Nufront CSC',
        'B8BB6D': 'ENERES',
        'B8BC1B': 'Huawei',
        'B8BD79': 'TrendPoint Systems',
        'B8BEBF': 'Cisco',
        'B8BF83': 'Intel',
        'B8C111': 'Apple',
        'B8C1A2': 'Dragon Path',
        'B8C227': 'PSTec',
        'B8C385': 'Huawei',
        'B8C3BF': 'Henan Chengshi NetWork',
        'B8C46F': 'PRI',
        'B8C68E': 'Samsung',
        'B8C716': 'Fiberhome',
        'B8C75D': 'Apple',
        'B8C855': 'Shanghai GBCOM Communication Technology',
        'B8CA3A': 'Dell',
        'B8CDA7': 'Maxeler',
        'B8D06F': 'Guangzhou Hkust FOK Ying Tung Research',
        'B8D49D': 'M Seven System',
        'B8D812': 'IEEE Registration Authority',
        'B8D9CE': 'Samsung',
        'B8DAF1': 'Strahlenschutz- Entwicklungs- und Ausruestungsgesellschaft mbH',
        'B8DAF7': 'Advanced Photonics',
        'B8DB1C': 'Integrated Device Technology',
        'B8DC87': 'IEEE Registration Authority',
        'B8DD71': 'Huawei',
        'B8DF6B': 'SpotCam',
        'B8E589': 'Payter',
        'B8E625': '2Wire',
        }

