rules:
  - name: Port Scan Detection
    type: port_scan
    threshold: 20
    time_window: 10
    alert_cooldown: 30

  - name: DNS Tunnel Detection
    type: dns_tunnel
    min_length: 30
    dot_count: 4